'use client';

import { useState, useEffect } from 'react';
import Navigation from '@/components/navigation';
import Footer from '@/components/footer';
import { Button } from '@/components/ui/button';

export default function SummaryPage() {
  const [realityCheck, setRealityCheck] = useState<any>(null);
  const [costCalc, setCostCalc] = useState<any>(null);
  const [routeCompare, setRouteCompare] = useState<any>(null);
  const [fitCheck, setFitCheck] = useState<any>(null);

  useEffect(() => {
    setRealityCheck(JSON.parse(localStorage.getItem('dharma_reality_check') || 'null'));
    setCostCalc(JSON.parse(localStorage.getItem('dharma_cost_calculator') || 'null'));
    setRouteCompare(JSON.parse(localStorage.getItem('dharma_route_compare') || 'null'));
    setFitCheck(JSON.parse(localStorage.getItem('dharma_fit_check') || 'null'));
  }, []);

  const generatePDF = () => {
    const content = `
DHARMA INSTITUTE OF PURPOSE
Personal Decision Journey Summary Report

${new Date().toLocaleDateString()}

==================================================
REALITY CHECK ASSESSMENT
==================================================
${
  realityCheck
    ? `
Pressure Category: ${realityCheck.category}
Pressure Score: ${realityCheck.total}/100

Key Drivers:
${realityCheck.drivers.map((d: string) => `• ${d}`).join('\n')}

${realityCheck.missingMiddle ? 'MISSING MIDDLE PATTERN DETECTED: Your income may appear sufficient on paper, but real-life financial pressure is high.' : ''}

Next Steps:
${realityCheck.nextSteps.map((s: string) => `→ ${s}`).join('\n')}
`
    : 'No data recorded yet'
}

==================================================
COST ANALYSIS
==================================================
${
  costCalc
    ? `
Annual Study Cost: R ${costCalc.totalAnnual.toLocaleString()}
Monthly Cost: R ${costCalc.monthlyCost.toLocaleString()}
Available Monthly Support: R ${costCalc.availableMonthly.toLocaleString()}
Monthly Gap: R ${costCalc.gap.toLocaleString()}

Affordability Status: ${costCalc.affordability}

${costCalc.flags.length > 0 ? `Warnings:\n${costCalc.flags.map((f: string) => `⚠ ${f}`).join('\n')}` : ''}
`
    : 'No data recorded yet'
}

==================================================
ROUTE COMPARISON
==================================================
${
  routeCompare
    ? `
Option A: ${routeCompare.optionA.name}
Risk Score: ${routeCompare.riskA}/100

Option B: ${routeCompare.optionB.name}
Risk Score: ${routeCompare.riskB}/100

Safer Option: ${routeCompare.safer === 'Equal' ? 'Both comparable' : `Option ${routeCompare.safer}`}
`
    : 'No data recorded yet'
}

==================================================
CAREER FIT ASSESSMENT
==================================================
${
  fitCheck
    ? `
Primary Career Fit: ${fitCheck.primaryFit}
Secondary Career Fit: ${fitCheck.secondaryFit}

Recommended Education Pathways:
${fitCheck.pathways.map((p: string, i: number) => `${i + 1}. ${p}`).join('\n')}

${fitCheck.warnings.length > 0 ? `\nConsiderations:\n${fitCheck.warnings.map((w: string) => `• ${w}`).join('\n')}` : ''}
`
    : 'No data recorded yet'
}

==================================================
OVERALL RECOMMENDATION
==================================================

Use the insights from your assessments to:
1. Understand your real affordability pressure
2. Calculate the true cost of your chosen path
3. Compare your options carefully
4. Align your choice with your career interests

Remember: Safer education decisions lead to better long-term outcomes.

This report was generated by Dharma Institute of Purpose
www.dharmainstitute.org
`;

    const element = document.createElement('a');
    element.setAttribute(
      'href',
      'data:text/plain;charset=utf-8,' + encodeURIComponent(content)
    );
    element.setAttribute('download', 'dharma-summary-report.txt');
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const hasAnyData = realityCheck || costCalc || routeCompare || fitCheck;

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navigation />

      <main className="flex-1">
        <div className="max-w-4xl mx-auto px-4" style={{ paddingTop: 'var(--section-padding-md)', paddingBottom: 'var(--section-padding-md)' }}>
          <div style={{ marginBottom: 'var(--space-xl)' }}>
            <h1 style={{ fontSize: 'var(--text-hero)', lineHeight: 'var(--heading-line-height)', marginBottom: 'var(--space-md)' }} className="font-bold text-foreground">
              Your Decision Journey Summary
            </h1>
            <p style={{ fontSize: 'var(--text-lead)', lineHeight: 'var(--line-height-base)' }} className="text-muted-foreground">
              Here is a complete overview of all your assessments and recommendations.
            </p>
          </div>

          {!hasAnyData ? (
            <div className="bg-card border border-border rounded-lg p-12 text-center" style={{ padding: 'var(--space-xl)', borderRadius: 'var(--card-radius)' }}>
              <p style={{ fontSize: 'var(--font-size-base)', lineHeight: 'var(--line-height-base)', marginBottom: 'var(--space-lg)' }} className="text-muted-foreground mb-6">
                You haven't completed any tools yet. Start the journey to build your summary.
              </p>
              <Button asChild>
                <a href="/start">
                  Begin Your Journey
                </a>
              </Button>
            </div>
          ) : (
            <div style={{ gap: 'var(--space-xl)' }} className="space-y-8">
              {realityCheck && (
                <section className="border-l-4 border-primary pl-6 py-6" style={{ paddingLeft: 'var(--space-lg)', paddingTop: 'var(--space-lg)', paddingBottom: 'var(--space-lg)' }}>
                  <div className="flex items-start justify-between mb-4" style={{ marginBottom: 'var(--space-md)' }}>
                    <h2 style={{ fontSize: 'var(--text-section)', lineHeight: 'var(--heading-line-height)' }} className="font-semibold text-foreground">
                      Reality Check Results
                    </h2>
                    <span className="bg-primary/10 text-primary px-3 py-1 rounded-full text-sm font-semibold" style={{ padding: 'var(--space-xs) var(--space-sm)', borderRadius: 'var(--card-radius)' }}>
                      Complete
                    </span>
                  </div>

                  <div className="bg-card border border-border rounded-lg p-6 mb-6" style={{ padding: 'var(--space-lg)', marginBottom: 'var(--space-lg)', borderRadius: 'var(--card-radius)' }}>
                    <p style={{ fontSize: 'var(--font-size-sm)', lineHeight: 'var(--line-height-base)', marginBottom: 'var(--space-xs)' }} className="text-muted-foreground mb-2">
                      Your Pressure Category
                    </p>
                    <h3 style={{ fontSize: 'var(--text-section)', lineHeight: 'var(--heading-line-height)', marginBottom: 'var(--space-md)' }} className="font-bold text-foreground">
                      {realityCheck.category}
                    </h3>
                    <p style={{ fontSize: 'var(--font-size-base)', lineHeight: 'var(--line-height-base)' }} className="text-foreground">
                      Pressure Score: <strong>{realityCheck.total}/100</strong>
                    </p>

                    {realityCheck.missingMiddle && (
                      <div style={{ marginTop: 'var(--space-md)', padding: 'var(--space-md)', borderRadius: 'var(--card-radius)' }} className="mt-4 p-4 bg-yellow-50 border border-yellow-200 rounded">
                        <p style={{ fontSize: 'var(--font-size-sm)' }} className="text-yellow-900">
                          Missing-middle pattern detected in your profile.
                        </p>
                      </div>
                    )}
                  </div>

                  {realityCheck.drivers.length > 0 && (
                    <div>
                      <h4 className="font-semibold text-foreground mb-3" style={{ marginBottom: 'var(--space-sm)' }}>
                        Key Pressure Drivers
                      </h4>
                      <ul style={{ gap: 'var(--space-sm)', marginBottom: 'var(--space-lg)' }} className="space-y-2 mb-6">
                        {realityCheck.drivers.map((d: string, i: number) => (
                          <li key={i} className="text-foreground flex gap-2" style={{ gap: 'var(--space-sm)' }}>
                            <span className="text-primary">•</span>
                            {d}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  <div>
                    <h4 className="font-semibold text-foreground mb-3" style={{ marginBottom: 'var(--space-sm)' }}>
                      Recommended Next Steps
                    </h4>
                    <ul style={{ gap: 'var(--space-sm)' }} className="space-y-2">
                      {realityCheck.nextSteps.map((s: string, i: number) => (
                        <li key={i} className="text-foreground flex gap-2" style={{ gap: 'var(--space-sm)' }}>
                          <span className="text-primary">→</span>
                          {s}
                        </li>
                      ))}
                    </ul>
                  </div>
                </section>
              )}

              {costCalc && (
                <section className="border-l-4 border-primary pl-6 py-6" style={{ paddingLeft: 'var(--space-lg)', paddingTop: 'var(--space-lg)', paddingBottom: 'var(--space-lg)' }}>
                  <div className="flex items-start justify-between mb-4" style={{ marginBottom: 'var(--space-md)' }}>
                    <h2 style={{ fontSize: 'var(--text-section)', lineHeight: 'var(--heading-line-height)' }} className="font-semibold text-foreground">
                      Cost Analysis
                    </h2>
                    <span className="bg-primary/10 text-primary px-3 py-1 rounded-full text-sm font-semibold" style={{ padding: 'var(--space-xs) var(--space-sm)', borderRadius: 'var(--card-radius)' }}>
                      Complete
                    </span>
                  </div>

                  <div className="grid md:grid-cols-2 gap-4 mb-6" style={{ gap: 'var(--space-md)', marginBottom: 'var(--space-lg)' }}>
                    <div className="bg-card border border-border rounded-lg p-4" style={{ padding: 'var(--space-md)', borderRadius: 'var(--card-radius)' }}>
                      <p style={{ fontSize: 'var(--font-size-xs)', lineHeight: 'var(--line-height-base)', marginBottom: 'var(--space-xs)' }} className="text-muted-foreground uppercase tracking-wide">
                        Annual Cost
                      </p>
                      <p style={{ fontSize: 'var(--text-section)', lineHeight: 'var(--heading-line-height)' }} className="font-bold text-foreground">
                        R {costCalc.totalAnnual.toLocaleString()}
                      </p>
                    </div>

                    <div className="bg-card border border-border rounded-lg p-4" style={{ padding: 'var(--space-md)', borderRadius: 'var(--card-radius)' }}>
                      <p style={{ fontSize: 'var(--font-size-xs)', lineHeight: 'var(--line-height-base)', marginBottom: 'var(--space-xs)' }} className="text-muted-foreground uppercase tracking-wide">
                        Monthly Gap
                      </p>
                      <p
                        className={`text-2xl font-bold ${
                          costCalc.gap <= 0 ? 'text-green-600' : 'text-red-600'
                        }`}
                        style={{ fontSize: 'var(--text-section)', lineHeight: 'var(--heading-line-height)' }}
                      >
                        {costCalc.gap > 0 ? '+' : ''}R{costCalc.gap.toLocaleString()}
                      </p>
                    </div>
                  </div>

                  <p style={{ fontSize: 'var(--font-size-base)', lineHeight: 'var(--line-height-base)', marginBottom: 'var(--space-md)' }} className="text-foreground mb-4">
                    <strong>Affordability Status:</strong> {costCalc.affordability}
                  </p>

                  {costCalc.flags.length > 0 && (
                    <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4" style={{ padding: 'var(--space-md)', borderRadius: 'var(--card-radius)' }}>
                      <p style={{ fontSize: 'var(--font-size-sm)', lineHeight: 'var(--line-height-base)', marginBottom: 'var(--space-sm)' }} className="font-semibold text-yellow-900 mb-2">
                        Cost Warnings
                      </p>
                      <ul style={{ gap: 'var(--space-xs)' }} className="space-y-1">
                        {costCalc.flags.map((f: string, i: number) => (
                          <li
                            key={i}
                            className="text-sm text-yellow-800 flex gap-2"
                            style={{ gap: 'var(--space-sm)' }}
                          >
                            <span>⚠</span>
                            {f}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </section>
              )}

              {routeCompare && (
                <section className="border-l-4 border-primary pl-6 py-6" style={{ paddingLeft: 'var(--space-lg)', paddingTop: 'var(--space-lg)', paddingBottom: 'var(--space-lg)' }}>
                  <div className="flex items-start justify-between mb-4" style={{ marginBottom: 'var(--space-md)' }}>
                    <h2 style={{ fontSize: 'var(--text-section)', lineHeight: 'var(--heading-line-height)' }} className="font-semibold text-foreground">
                      Route Comparison
                    </h2>
                    <span className="bg-primary/10 text-primary px-3 py-1 rounded-full text-sm font-semibold" style={{ padding: 'var(--space-xs) var(--space-sm)', borderRadius: 'var(--card-radius)' }}>
                      Complete
                    </span>
                  </div>

                  <div className="grid md:grid-cols-2 gap-4" style={{ gap: 'var(--space-md)' }}>
                    {[
                      {
                        letter: 'A',
                        option: routeCompare.optionA,
                        risk: routeCompare.riskA,
                      },
                      {
                        letter: 'B',
                        option: routeCompare.optionB,
                        risk: routeCompare.riskB,
                      },
                    ].map(({ letter, option, risk }) => (
                      <div
                        key={letter}
                        className={`border rounded-lg p-4 ${
                          routeCompare.safer === letter
                            ? 'border-green-400 bg-green-50'
                            : 'border-border'
                        }`}
                        style={{ padding: 'var(--space-md)', borderRadius: 'var(--card-radius)' }}
                      >
                        <h4 className="font-semibold text-foreground mb-2" style={{ marginBottom: 'var(--space-xs)' }}>
                          {option.name}
                          {routeCompare.safer === letter && (
                            <span className="ml-2 text-xs font-normal text-green-700 bg-green-100 px-2 py-1 rounded" style={{ marginLeft: 'var(--space-xs)', padding: 'var(--space-xs) var(--space-sm)', borderRadius: 'var(--card-radius)' }}>
                              Safer
                            </span>
                          )}
                        </h4>
                        <p style={{ fontSize: 'var(--font-size-sm)', lineHeight: 'var(--line-height-base)', marginBottom: 'var(--space-xs)' }} className="text-muted-foreground mb-2">
                          Cost: R {option.cost.toLocaleString()}
                        </p>
                        <p style={{ fontSize: 'var(--font-size-sm)', lineHeight: 'var(--line-height-base)' }} className="text-muted-foreground">
                          Risk Score: {risk}/100
                        </p>
                      </div>
                    ))}
                  </div>
                </section>
              )}

              {fitCheck && (
                <section className="border-l-4 border-primary pl-6 py-6" style={{ paddingLeft: 'var(--space-lg)', paddingTop: 'var(--space-lg)', paddingBottom: 'var(--space-lg)' }}>
                  <div className="flex items-start justify-between mb-4" style={{ marginBottom: 'var(--space-md)' }}>
                    <h2 style={{ fontSize: 'var(--text-section)', lineHeight: 'var(--heading-line-height)' }} className="font-semibold text-foreground">
                      Career Fit Assessment
                    </h2>
                    <span className="bg-primary/10 text-primary px-3 py-1 rounded-full text-sm font-semibold" style={{ padding: 'var(--space-xs) var(--space-sm)', borderRadius: 'var(--card-radius)' }}>
                      Complete
                    </span>
                  </div>

                  <div className="bg-card border border-border rounded-lg p-6 mb-6" style={{ padding: 'var(--space-lg)', marginBottom: 'var(--space-lg)', borderRadius: 'var(--card-radius)' }}>
                    <p style={{ fontSize: 'var(--font-size-sm)', lineHeight: 'var(--line-height-base)', marginBottom: 'var(--space-xs)' }} className="text-muted-foreground mb-2">
                      Primary Career Fit
                    </p>
                    <h3 style={{ fontSize: 'var(--text-section)', lineHeight: 'var(--heading-line-height)' }} className="font-bold text-foreground">
                      {fitCheck.primaryFit}
                    </h3>
                  </div>

                  {fitCheck.pathways.length > 0 && (
                    <div>
                      <h4 className="font-semibold text-foreground mb-3" style={{ marginBottom: 'var(--space-sm)' }}>
                        Recommended Education Pathways
                      </h4>
                      <ul style={{ gap: 'var(--space-sm)' }} className="space-y-2">
                        {fitCheck.pathways.map((p: string, i: number) => (
                          <li key={i} className="text-foreground flex gap-2" style={{ gap: 'var(--space-sm)' }}>
                            <span className="text-primary">{i + 1}.</span>
                            {p}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </section>
              )}

              {/* Overall Signal */}
              <section className="border-l-4 border-accent pl-6 py-6 bg-accent/5 rounded-r-lg" style={{ paddingLeft: 'var(--space-lg)', paddingTop: 'var(--space-lg)', paddingBottom: 'var(--space-lg)', borderRadius: '0 var(--card-radius) var(--card-radius) 0' }}>
                <h2 style={{ fontSize: 'var(--text-section)', lineHeight: 'var(--heading-line-height)', marginBottom: 'var(--space-md)' }} className="font-semibold text-foreground mb-4">
                  Your Overall Signal
                </h2>
                <p style={{ fontSize: 'var(--font-size-base)', lineHeight: 'var(--line-height-base)' }} className="text-foreground leading-relaxed">
                  Based on your assessments, you have a clearer picture of your affordability,
                  the true cost of your options, which routes are safest, and what careers align
                  with your interests. Use these insights to make a confident, informed decision
                  about your education and career path.
                </p>
              </section>

              {/* Actions */}
              <div style={{ borderTop: '1px solid var(--border)', paddingTop: 'var(--space-xl)', gap: 'var(--space-sm)' }} className="border-t border-border pt-8 space-y-3">
                <Button onClick={generatePDF} className="w-full">
                  Download Report
                </Button>

                <Button variant="outline" asChild className="w-full">
                  <a href="/contact">
                    Book a Guidance Session
                  </a>
                </Button>

                <Button
                  variant="ghost"
                  onClick={() => {
                    localStorage.removeItem('dharma_reality_check');
                    localStorage.removeItem('dharma_cost_calculator');
                    localStorage.removeItem('dharma_route_compare');
                    localStorage.removeItem('dharma_fit_check');
                    window.location.reload();
                  }}
                  className="w-full"
                >
                  Clear Results & Start Over
                </Button>
              </div>
            </div>
          )}
        </div>
      </main>

      <Footer />
    </div>
  );
}
